{
 "title": "Fleet Viewer",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "imei",
    "label": "IMEI",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"telematics\",\r\n  tag: \"imei\",\r\n  predicate: (r) => r._measurement == \"teltonika_avl\"\r\n)\r\n"
    }
   }
  ]
 },
 "panels": [
  { "title": "Vehicle Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Car Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telematics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"teltonika_avl\")\r\n  |> filter(fn: (r) => r._field == \"External_Voltage\")\r\n  |> filter(fn: (r) => r.imei == \"${imei}\")\r\n"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telematics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"teltonika_avl\")\r\n  |> filter(fn: (r) => r._field == \"altitude\")\r\n  |> filter(fn: (r) => r.imei == \"${imei}\")\r\n"
    }
   ]
  },
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"telematics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"teltonika_avl\")\r\n  |> filter(fn: (r) => r._field == \"latitude\" or r._field == \"longitude\")\r\n  |> filter(fn: (r) => r.imei == \"${imei}\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"imei\"])"
    }
   ]
  },
  {
   "title": "Ignition",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telematics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"teltonika_avl\")\r\n  |> filter(fn: (r) => r._field == \"Ignition\")\r\n  |> filter(fn: (r) => r.imei == \"${imei}\")\r\n"
    }
   ]
  },
  {
   "title": "Odometer",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telematics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"teltonika_avl\")\r\n  |> filter(fn: (r) => r._field == \"Total_Odometer\")\r\n  |> filter(fn: (r) => r.imei == \"${imei}\")\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000}))\r\n"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telematics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"teltonika_avl\")\r\n  |> filter(fn: (r) => r._field == \"speed\")\r\n  |> filter(fn: (r) => r.imei == \"${imei}\")\r\n"
    }
   ]
  },
  {
   "title": "Angle",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telematics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"teltonika_avl\")\r\n  |> filter(fn: (r) => r._field == \"angle\")\r\n  |> filter(fn: (r) => r.imei == \"${imei}\")\r\n"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"telematics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"teltonika_avl\")\r\n  |> filter(fn: (r) => r._field == \"speed\")\r\n  |> filter(fn: (r) => r.imei == \"${imei}\")\r\n"
    }
   ]
  },
  { "title": "GNSS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "GNSS Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telematics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"teltonika_avl\")\r\n  |> filter(fn: (r) => r._field == \"GNSS_Status\")\r\n  |> filter(fn: (r) => r.imei == \"${imei}\")\r\n"
    }
   ]
  },
  {
   "title": "Satellites",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telematics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"teltonika_avl\")\r\n  |> filter(fn: (r) => r._field == \"satellites\")\r\n  |> filter(fn: (r) => r.imei == \"${imei}\")\r\n"
    }
   ]
  },
  {
   "title": "GNSS HDOP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telematics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"teltonika_avl\")\r\n  |> filter(fn: (r) => r._field == \"GNSS_HDOP\")\r\n  |> filter(fn: (r) => r.imei == \"${imei}\")\r\n"
    }
   ]
  },
  {
   "title": "GNSS PDOP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telematics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"teltonika_avl\")\r\n  |> filter(fn: (r) => r._field == \"GNSS_PDOP\")\r\n  |> filter(fn: (r) => r.imei == \"${imei}\")\r\n"
    }
   ]
  },
  {
   "title": "Movement",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telematics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"teltonika_avl\")\r\n  |> filter(fn: (r) => r._field == \"Movement\")\r\n  |> filter(fn: (r) => r.imei == \"${imei}\")\r\n"
    }
   ]
  },
  { "title": "Module Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Active GSM Operator",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telematics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"teltonika_avl\")\r\n  |> filter(fn: (r) => r._field == \"Active_GSM_Operator\")\r\n  |> filter(fn: (r) => r.imei == \"${imei}\")\r\n"
    }
   ]
  },
  {
   "title": "GSM Signal",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telematics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"teltonika_avl\")\r\n  |> filter(fn: (r) => r._field == \"GSM_Signal\")\r\n  |> filter(fn: (r) => r.imei == \"${imei}\")\r\n"
    }
   ]
  },
  {
   "title": "Sleep Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telematics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"teltonika_avl\")\r\n  |> filter(fn: (r) => r._field == \"Sleep_Mode\")\r\n  |> filter(fn: (r) => r.imei == \"${imei}\")\r\n"
    }
   ]
  },
  {
   "title": "Last Contact & IP Address",
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 9, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"telematics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"teltonika_avl\" and\r\n    r._field == \"ip\" and\r\n    r.imei == \"${imei}\"\r\n  )\r\n  |> group(columns: [\"_measurement\",\"_field\",\"imei\"])\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Backup Battery",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telematics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"teltonika_avl\")\r\n  |> filter(fn: (r) => r._field == \"Battery_Voltage\")\r\n  |> filter(fn: (r) => r.imei == \"${imei}\")\r\n"
    }
   ]
  },
  {
   "title": "Backup Battery",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telematics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"teltonika_avl\")\r\n  |> filter(fn: (r) => r._field == \"Battery_Current\")\r\n  |> filter(fn: (r) => r.imei == \"${imei}\")\r\n"
    }
   ]
  }
 ]
}