package io.felixtech.avl8edecoder;

import java.util.Map;

public final class AVLMap {
    private AVLMap() {}

    /**
     * Teltonika FMC150 AVL Mapping
     */
    public static final Map<Integer, String> AVL_NAMES = Map.<Integer, String>ofEntries(
            Map.entry(239,"Ignition"),
            Map.entry(240,"Movement"),
            Map.entry(80,"Data Mode"),
            Map.entry(21,"GSM Signal"),
            Map.entry(200,"Sleep Mode"),
            Map.entry(69,"GNSS Status"),
            Map.entry(181,"GNSS PDOP"),
            Map.entry(182,"GNSS HDOP"),
            Map.entry(66,"External Voltage"),
            Map.entry(24,"Speed"),
            Map.entry(205,"GSM Cell ID"),
            Map.entry(206,"GSM Area Code"),
            Map.entry(67,"Battery Voltage"),
            Map.entry(68,"Battery Current"),
            Map.entry(241,"Active GSM Operator"),
            Map.entry(199,"Trip Odometer"),
            Map.entry(16,"Total Odometer"),
            Map.entry(1,"Digital Input 1"),
            Map.entry(9,"Analog Input 1"),
            Map.entry(179,"Digital Output 1"),
            Map.entry(12,"Fuel Used GPS"),
            Map.entry(13,"Fuel Rate GPS"),
            Map.entry(17,"Axis X"),
            Map.entry(18,"Axis Y"),
            Map.entry(19,"Axis Z"),
            Map.entry(11,"ICCID1"),
            Map.entry(10,"SD Status"),
            Map.entry(2,"Digital Input 2"),
            Map.entry(3,"Digital Input 3"),
            Map.entry(6,"Analog Input 2"),
            Map.entry(180,"Digital Output 2"),
            Map.entry(72,"Dallas Temperature 1"),
            Map.entry(73,"Dallas Temperature 2"),
            Map.entry(74,"Dallas Temperature 3"),
            Map.entry(75,"Dallas Temperature 4"),
            Map.entry(76,"Dallas Temperature ID 1"),
            Map.entry(77,"Dallas Temperature ID 2"),
            Map.entry(79,"Dallas Temperature ID 3"),
            Map.entry(71,"Dallas Temperature ID 4"),
            Map.entry(78,"iButton"),
            Map.entry(207,"RFID"),
            Map.entry(201,"LLS 1 Fuel Level"),
            Map.entry(202,"LLS 1 Temperature"),
            Map.entry(203,"LLS 2 Fuel Level"),
            Map.entry(204,"LLS 2 Temperature"),
            Map.entry(210,"LLS 3 Fuel Level"),
            Map.entry(211,"LLS 3 Temperature"),
            Map.entry(212,"LLS 4 Fuel Level"),
            Map.entry(213,"LLS 4 Temperature"),
            Map.entry(214,"LLS 5 Fuel Level"),
            Map.entry(215,"LLS 5 Temperature"),
            Map.entry(15,"Eco Score"),
            Map.entry(113,"Battery Level"),
            Map.entry(238,"User ID"),
            Map.entry(237,"Network Type"),
            Map.entry(8,"Authorized iButton"),
            Map.entry(4,"Pulse Counter Din1"),
            Map.entry(5,"Pulse Counter Din2"),
            Map.entry(263,"BT Status"),
            Map.entry(264,"Barcode ID"),
            Map.entry(269,"Escort LLS Temperature #1"),
            Map.entry(271,"Escort LLS Battery Voltage #1"),
            Map.entry(272,"Escort LLS Temperature #2"),
            Map.entry(274,"Escort LLS Battery Voltage #2"),
            Map.entry(275,"Escort LLS Temperature #3"),
            Map.entry(277,"Escort LLS Battery Voltage #3"),
            Map.entry(278,"Escort LLS Temperature #4"),
            Map.entry(280,"Escort LLS Battery Voltage #4"),
            Map.entry(303,"Instant Movement"),
            Map.entry(327,"UL202-02 Sensor Fuel level"),
            Map.entry(483,"UL202-02 Sensor Status"),
            Map.entry(380,"Digital output 3"),
            Map.entry(381,"Ground Sense"),
            Map.entry(387,"ISO6709 Coordinates"),
            Map.entry(636,"UMTS/LTE Cell ID"),
            Map.entry(403,"Driver Name"),
            Map.entry(404,"Driver card license type"),
            Map.entry(405,"Driver Gender"),
            Map.entry(406,"Driver Card ID"),
            Map.entry(407,"Driver card expiration date"),
            Map.entry(408,"Driver Card place of issue"),
            Map.entry(409,"Driver Status Event"),
            Map.entry(329,"AIN Speed"),
            Map.entry(500,"MSP500 vendor name"),
            Map.entry(501,"MSP500 vehicle number"),
            Map.entry(502,"MSP500 speed sensor"),
            Map.entry(622,"Frequency DIN1"),
            Map.entry(623,"Frequency DIN2"),
            Map.entry(637,"Wake Reason"),
            Map.entry(155,"Geofence zone 01"),
            Map.entry(156,"Geofence zone 02"),
            Map.entry(157,"Geofence zone 03"),
            Map.entry(158,"Geofence zone 04"),
            Map.entry(159,"Geofence zone 05"),
            Map.entry(61,"Geofence zone 06"),
            Map.entry(62,"Geofence zone 07"),
            Map.entry(63,"Geofence zone 08"),
            Map.entry(64,"Geofence zone 09"),
            Map.entry(65,"Geofence zone 10"),
            Map.entry(70,"Geofence zone 11"),
            Map.entry(88,"Geofence zone 12"),
            Map.entry(91,"Geofence zone 13"),
            Map.entry(92,"Geofence zone 14"),
            Map.entry(93,"Geofence zone 15"),
            Map.entry(94,"Geofence zone 16"),
            Map.entry(95,"Geofence zone 17"),
            Map.entry(96,"Geofence zone 18"),
            Map.entry(97,"Geofence zone 19"),
            Map.entry(98,"Geofence zone 20"),
            Map.entry(99,"Geofence zone 21"),
            Map.entry(153,"Geofence zone 22"),
            Map.entry(154,"Geofence zone 23"),
            Map.entry(190,"Geofence zone 24"),
            Map.entry(191,"Geofence zone 25"),
            Map.entry(192,"Geofence zone 26"),
            Map.entry(193,"Geofence zone 27"),
            Map.entry(194,"Geofence zone 28"),
            Map.entry(195,"Geofence zone 29"),
            Map.entry(196,"Geofence zone 30"),
            Map.entry(197,"Geofence zone 31"),
            Map.entry(198,"Geofence zone 32"),
            Map.entry(208,"Geofence zone 33"),
            Map.entry(209,"Geofence zone 34"),
            Map.entry(216,"Geofence zone 35"),
            Map.entry(217,"Geofence zone 36"),
            Map.entry(218,"Geofence zone 37"),
            Map.entry(219,"Geofence zone 38"),
            Map.entry(220,"Geofence zone 39"),
            Map.entry(221,"Geofence zone 40"),
            Map.entry(222,"Geofence zone 41"),
            Map.entry(223,"Geofence zone 42"),
            Map.entry(224,"Geofence zone 43"),
            Map.entry(225,"Geofence zone 44"),
            Map.entry(226,"Geofence zone 45"),
            Map.entry(227,"Geofence zone 46"),
            Map.entry(228,"Geofence zone 47"),
            Map.entry(229,"Geofence zone 48"),
            Map.entry(230,"Geofence zone 49"),
            Map.entry(231,"Geofence zone 50"),
            Map.entry(175,"Auto Geofence"),
            Map.entry(250,"Trip"),
            Map.entry(255,"Over Speeding"),
            Map.entry(257,"Crash trace data"),
            Map.entry(285,"Blood alcohol content"),
            Map.entry(251,"Idling"),
            Map.entry(253,"Green driving type"),
            Map.entry(246,"Towing"),
            Map.entry(252,"Unplug"),
            Map.entry(247,"Crash detection"),
            Map.entry(248,"Immobilizer"),
            Map.entry(254,"Green Driving Value"),
            Map.entry(249,"Jamming"),
            Map.entry(14,"ICCID2"),
            Map.entry(243,"Green driving event duration"),
            Map.entry(236,"Alarm"),
            Map.entry(258,"EcoMaximum"),
            Map.entry(259,"EcoAverage"),
            Map.entry(260,"EcoDuration"),
            Map.entry(283,"Driving State"),
            Map.entry(284,"Driving Records"),
            Map.entry(391,"Private mode"),
            Map.entry(317,"Crash event counter"),
            Map.entry(449,"Ignition On Counter"),
            Map.entry(256,"VIN"),
            Map.entry(30,"Number of DTC"),
            Map.entry(31,"Engine Load"),
            Map.entry(32,"Coolant Temperature"),
            Map.entry(33,"Short Fuel Trim"),
            Map.entry(34,"Fuel pressure"),
            Map.entry(35,"Intake MAP"),
            Map.entry(36,"Engine RPM"),
            Map.entry(37,"Vehicle Speed"),
            Map.entry(38,"Timing Advance"),
            Map.entry(39,"Intake Air Temperature"),
            Map.entry(40,"MAF"),
            Map.entry(41,"Throttle Position"),
            Map.entry(42,"Runtime since engine start"),
            Map.entry(43,"Distance Traveled MIL On"),
            Map.entry(44,"Relative Fuel Rail Pressure"),
            Map.entry(45,"Direct Fuel Rail Pressure"),
            Map.entry(46,"Commanded EGR"),
            Map.entry(47,"EGR Error"),
            Map.entry(48,"Fuel Level"),
            Map.entry(49,"Distance Since Codes Clear"),
            Map.entry(50,"Barometic Pressure"),
            Map.entry(51,"Control Module Voltage"),
            Map.entry(52,"Absolute Load Value"),
            Map.entry(759,"Fuel Type"),
            Map.entry(53,"Ambient Air Temperature"),
            Map.entry(54,"Time Run With MIL On"),
            Map.entry(55,"Time Since Codes Cleared"),
            Map.entry(56,"Absolute Fuel Rail Pressure"),
            Map.entry(57,"Hybrid battery pack life"),
            Map.entry(58,"Engine Oil Temperature"),
            Map.entry(59,"Fuel injection timing"),
            Map.entry(543,"Hybrid System Voltage"),
            Map.entry(544,"Hybrid System Current"),
            Map.entry(281,"Fault Codes"),
            Map.entry(60,"Fuel Rate"),
            Map.entry(385,"Beacon"),
            Map.entry(25,"BLE Temperature #1"),
            Map.entry(26,"BLE Temperature #2"),
            Map.entry(27,"BLE Temperature #3"),
            Map.entry(28,"BLE Temperature #4"),
            Map.entry(29,"BLE Battery #1"),
            Map.entry(20,"BLE Battery #2"),
            Map.entry(22,"BLE Battery #3"),
            Map.entry(23,"BLE Battery #4"),
            Map.entry(86,"BLE Humidity #1"),
            Map.entry(104,"BLE Humidity #2"),
            Map.entry(106,"BLE Humidity #3"),
            Map.entry(108,"BLE Humidity #4"),
            Map.entry(270,"BLE Fuel Level #1"),
            Map.entry(273,"BLE Fuel Level #2"),
            Map.entry(276,"BLE Fuel Level #3"),
            Map.entry(279,"BLE Fuel Level #4"),
            Map.entry(306,"BLE Fuel Frequency #1"),
            Map.entry(307,"BLE Fuel Frequency #2"),
            Map.entry(308,"BLE Fuel Frequency #3"),
            Map.entry(309,"BLE Fuel Frequency #4"),
            Map.entry(335,"BLE Luminosity #1"),
            Map.entry(336,"BLE Luminosity #2"),
            Map.entry(337,"BLE Luminosity #3"),
            Map.entry(338,"BLE Luminosity #4"),
            Map.entry(331,"BLE 1 Custom #1"),
            Map.entry(463,"BLE 1 Custom #2"),
            Map.entry(464,"BLE 1 Custom #3"),
            Map.entry(465,"BLE 1 Custom #4"),
            Map.entry(466,"BLE 1 Custom #5"),
            Map.entry(332,"BLE 2 Custom #1"),
            Map.entry(467,"BLE 2 Custom #2"),
            Map.entry(468,"BLE 2 Custom #3"),
            Map.entry(469,"BLE 2 Custom #4"),
            Map.entry(470,"BLE 2 Custom #5"),
            Map.entry(333,"BLE 3 Custom #1"),
            Map.entry(471,"BLE 3 Custom #2"),
            Map.entry(472,"BLE 3 Custom #3"),
            Map.entry(473,"BLE 3 Custom #4"),
            Map.entry(474,"BLE 3 Custom #5"),
            Map.entry(334,"BLE 4 Custom #1"),
            Map.entry(475,"BLE 4 Custom #2"),
            Map.entry(476,"BLE 4 Custom #3"),
            Map.entry(477,"BLE 4 Custom #4"),
            Map.entry(478,"BLE 4 Custom #5"),
            Map.entry(115,"Engine Coolant Temperature"),
            Map.entry(85,"Engine Speed"),
            Map.entry(81,"Vehicle Speed"),
            Map.entry(82,"Throttle position"),
            Map.entry(89,"Fuel Level"),
            Map.entry(87,"Total Mileage"),
            Map.entry(84,"Fuel Level"),
            Map.entry(400,"Distance till next servicing"),
            Map.entry(866,"Remaining distance"),
            Map.entry(940,"Seat Belt Status Front Left"),
            Map.entry(941,"Seat Belt Status Front Right"),
            Map.entry(942,"Seat Belt Status Rear Left"),
            Map.entry(943,"Seat Belt Status Rear Right"),
            Map.entry(654,"Door Status Front Left"),
            Map.entry(655,"Door Status Front Right"),
            Map.entry(656,"Door Status Rear Left"),
            Map.entry(657,"Door Status Rear Right"),
            Map.entry(913,"Bonnet status"),
            Map.entry(658,"Trunk status"),
            Map.entry(152,"HVBattery charge level"),
            Map.entry(937,"Cruise Control Active"),
            Map.entry(910,"Brake switch"),
            Map.entry(928,"Lamp Side"),
            Map.entry(929,"Lamp Dimmed"),
            Map.entry(930,"Lamp Reflector"),
            Map.entry(932,"Lamp Fog Front"),
            Map.entry(931,"Lamp Fog Rear"),
            Map.entry(653,"Parking Brake State"),
            Map.entry(911,"Clutch switch"),
            Map.entry(168,"Battery Voltage"),
            Map.entry(662,"Central Lock"),
            Map.entry(944,"Seat Belt Status Rear Center"),
            Map.entry(1112,"EV HV Battery Voltage"),
            Map.entry(1113,"EV HV Battery Current"),
            Map.entry(1157,"EV HV Battery Power"),
            Map.entry(105,"Total Mileage Counted"),
            Map.entry(107,"Fuel Consumed Counted"),
            Map.entry(1156,"HV Battery Recuperated Energy"),
            Map.entry(1155,"HV Battery Consumed Energy"),
            Map.entry(83,"Fuel Consumption"),
            Map.entry(1413,"Turn signal left"),
            Map.entry(1414,"Turn signal right"),
            Map.entry(325,"VIN"),
            Map.entry(1418,"Electric motor temperature"),
            Map.entry(1415,"Charge port flap"),
            Map.entry(914,"BAT Battery Charge Cable Plugged in"),
            Map.entry(915,"HVBattery charge state"),
            Map.entry(660,"Automatic Transmission Lever State P"),
            Map.entry(661,"Automatic Transmission Lever State R"),
            Map.entry(659,"Automatic Transmission Lever State N"),
            Map.entry(927,"Automatic Transmission Lever State D"),
            Map.entry(1158,"Engine Oil Pressure"),
            Map.entry(1159,"Engine Oil Level"),
            Map.entry(1137,"Steering Wheel Angle"),
            Map.entry(1358,"Steering Wheel Direction Left"),
            Map.entry(1359,"Steering Wheel Direction Right"),
            Map.entry(1360,"EV ECO Switch"),
            Map.entry(1362,"Position Status of All doors"),
            Map.entry(1331,"Transmission Selected Gear"),
            Map.entry(1332,"Transmission Current Gear"),
            Map.entry(1333,"Steering wheel turn counter"),
            Map.entry(1361,"Ramp/WheelChairLift Status"),
            Map.entry(1335,"Exhaust Fluid Tank level (AdBlue)"),
            Map.entry(1336,"Bellow pressure FR axle"),
            Map.entry(1337,"Bellow pressure FL axle"),
            Map.entry(1338,"Bellow pressure RR axle"),
            Map.entry(1339,"Bellow pressure RL axle"),
            Map.entry(1364,"Vehicle Overspeed"),
            Map.entry(1220,"Gross Combination Vehicle Weight"),
            Map.entry(1341,"Gaseous Fuel Rate"),
            Map.entry(1366,"Alternator Status 1"),
            Map.entry(1367,"Alternator Status 2"),
            Map.entry(1368,"Alternator Status 3"),
            Map.entry(1369,"Alternator Status 4"),
            Map.entry(102,"Engine Total Hours"),
            Map.entry(103,"Engine Total Hours (counted)"),
            Map.entry(118,"Axle 1 Load"),
            Map.entry(119,"Axle 2 Load"),
            Map.entry(120,"Axle 3 Load"),
            Map.entry(121,"Axle 4 Load"),
            Map.entry(122,"Axle 5 Load"),
            Map.entry(1342,"Axle 6 Load"),
            Map.entry(1270,"Engine Oil Temperature"),
            Map.entry(1343,"Engine Fuel Temperature"),
            Map.entry(1344,"Cruise Control Set Speed"),
            Map.entry(1345,"Instant Fuel Economy"),
            Map.entry(1352,"Engine Air Intake Pressure"),
            Map.entry(1373,"Door 1 Lock Status"),
            Map.entry(1374,"Door 2 Lock Status"),
            Map.entry(1375,"Door 3 Lock Status"),
            Map.entry(1376,"Door 4 Lock Status"),
            Map.entry(936,"AC On"),
            Map.entry(956,"ESP Enabled"),
            Map.entry(114,"Engine Torque"),
            Map.entry(1396,"Ambient Air Temperature"),
            Map.entry(1397,"ASR Enabled"),
            Map.entry(1416,"Windscreen Wiper"),
            Map.entry(946,"PTO state"),
            Map.entry(1116,"Max Road Speed"),
            Map.entry(1117,"Exceeded Road Speed"),
            Map.entry(1205,"AF Speed Limit Sign Recognized"),
            Map.entry(1207,"AF Exceeding Speed Indicated By Speed Limit Sign")
        );
}
